import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import "./globals.css";

const nanumGothic = Nanum_Gothic({ subsets: ["latin"], weight: ["700"] });

export const metadata: Metadata = {
  title: "최정윤 | 프론트엔드 개발자",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nanumGothic.className}>{children}</body>
    </html>
  );
}
